### ISSUE TITLE
Research correlation of 4xx errors with error spikes

### ISSUE THREAD

**Issue by moliva** [decentraland/matrix-playbook#100]
There is a correlation in the error rate with 4xx errors, resulting in recurrent error spikes during the weeks.

Research this behavior and diagnose the issue, potentially coming with a plan for a fix.

![Image](https://user-images.githubusercontent.com/3766397/189665251-921056de-c700-4db3-a2fc-d3531dff4875.png)
![Image](https://user-images.githubusercontent.com/3766397/189665250-40ae0259-fe81-4905-90d2-bf54812a5c41.png)

**Comment by lauti7** [comment]
We looked into this issue and analyzed the last two available 4xx spikes (in the previous 7 days) in Grafana. The first one was on **10/13**, and the second one was on **10/14**. 
- **10/13 - From 13:50 to 14:53:**
We looked for Ngnix logs with status code 4xx with regex: `B 4\d{2} "` and we didn't find as many as we expected or as the image below displayed. However, the principal 4xx codes found: `403` -> for `/_matrix/client/r0/login` (23), `404` -> for `/_matrix/client/r0/directory/room/{ID}` (18), and `405` (POST) -> for `/_matrix/static/` with query params (28). 
Besides this, many `404` errors (1.2k) are not matched with the above regex but with `\[error\]` (Ngnix returns a 404 error page for these logs). These `404` errors were a lot more than those matched with `B 4\d{2} "`. Some of them are for `https://synapse.decentraland.org/health`, but the rest are for random URLs that look like someone is trying to get something private from DCL systems or just scraping. Some of the rest URLs are like this or more random: 
  -  `https://synapse.decentraland.org/apt/v1/context`
  - `https://synapse.decentraland.org/api/get_device_details`
  - `https://synapse.decentraland.org/login/system`
  - `https://synapse.decentraland.org/debug/`
  - `https://synapse.decentraland.org/php/login.php`
 
 ![Screen Shot 2022-10-14 at 15 19 10](https://user-images.githubusercontent.com/26555310/195923915-02be95ac-3b33-4a88-9da2-e4c10d98c691.png)


- **10/14 - From 11:35 to 12:35:**
This day was a lot more 4xx errors than 10/13, the spike increased a quite bit. As in the above case, we started looking for Ngnix logs with the same regex and the result was the same, not as many logs as we expected or as the image below displayed. The `405` POST requests for `/_matrix/static/` with queries (29) remain as in the 10/13 case, `403` for  `/_matrix/client/r0/login` (21) too. The difference for this day is that there were a lot of requests with status code `401` due to a [Web Crawler ](https://www.comscore.com/Web-Crawler) that was sending requests to the `/sync` endpoint. Moreover, there were multiple `404` errors, double that on 10/13, 3.6k. And these last errors were like on 10/13, someone scraping or trying random URLs to get into DCL systems or to obtain something private. 

![Screen Shot 2022-10-14 at 16 13 04](https://user-images.githubusercontent.com/26555310/195924055-d623f064-5a9e-4e0c-ae1b-11d2510b54fe.png)
